### ISSUE TITLE
Removes commands completion in keybindings.json

### ISSUE THREAD

**Issue by zardoy** [usernamehw/vscode-commands#53] opened 2023-07-07 14:23 UTC
Bug STR: 
Vscode adds commands completion via JSON definition. It would be good to not remove keybindings.json completions in the following location (`|`):

```json
[
  {
    "command": "|",
    "when": "isWindows",
    "key": "ctrl+p"
  }
]
```
Command: `> Preferences: Open Keyboard Shortcuts (JSON)`

**Comment by usernamehw** [comment] 2023-07-07 15:26
It shouldn't. Cannot reproduce.

**Comment by zardoy** [comment] 2023-07-07 21:15
Ok, sorry, STR wasn't clear. I don't have one keybinding actually, I have thousands of them :) That's because I turned off platform-specific keybindings sync, so I can make platform-agnostic shortcuts from any platform like `ctrlCmd+n`. So if you add them in a way like this:

```ts
let str
for (let i = 0; i < 1000; i++) {
    str += '{"command": ""},\n'
}

console.log(`[${str}]`)
```

it won't display any suggestions in my case/

**Comment by usernamehw** [comment] 2023-07-08 07:39
Don't really know why this happens. You are welcome to investigate.

**Comment by usernamehw** [comment] 2023-08-21 09:55
Closing as no action planned.

**Closed by usernamehw** 2023-08-21 09:55 UTC
